{"name": "test_fail2", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail2():\n>       assert False\nE       assert False\n\ntest_fail.py:6: AssertionError"}, "start": 1674214156187, "stop": 1674214156188, "uuid": "f84b6c22-ee59-4305-b4d1-f6c44e95658e", "historyId": "d9abb2df8f63b2adf55d2ccff200c9b1", "testCaseId": "4f39991870c75bdeb73cdb83d5f0a386", "fullName": "test_fail#test_fail2", "labels": [{"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MacBook-Pro-Aleksej.local"}, {"name": "thread", "value": "30407-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_fail"}]}