{"name": "test_fail", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail():\n>       assert False\nE       assert False\n\ntest_fail.py:2: AssertionError"}, "start": 1674214156132, "stop": 1674214156133, "uuid": "48b3afc0-134c-4ad9-95e2-8739f3874d61", "historyId": "caa7039c055cc58869beb542caf69443", "testCaseId": "9672b283b54d126f0c15f3d442a1834e", "fullName": "test_fail#test_fail", "labels": [{"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MacBook-Pro-Aleksej.local"}, {"name": "thread", "value": "30407-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_fail"}]}