{"name": "test_fail3", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail3():\n>       assert False\nE       assert False\n\ntest_fail.py:10: AssertionError"}, "start": 1674214156193, "stop": 1674214156193, "uuid": "2a38b911-6d0d-4119-aa1a-65d072b62672", "historyId": "8070e1ccd25558cb8bf0cd371aca5015", "testCaseId": "f11f56cf34ffc3e725a345f91d11d841", "fullName": "test_fail#test_fail3", "labels": [{"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MacBook-Pro-Aleksej.local"}, {"name": "thread", "value": "30407-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_fail"}]}